name: Pip audit

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  security:
    name: Run pip-audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install --no-cache-dir --upgrade --force-reinstall 'setuptools>=65.5.1'

      - name: Pip audit
        uses: pypa/gh-action-pip-audit@v1.0.8
