name: Static typing with Mypy

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  mypy:
    name: Run Mypy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requirements
        run: pip install -r requirements.txt -r requirements.dev.txt

      - name: Mypy check
        run: mypy .
